# Note that while Conda accepts a package name of "dbus-c++", Anaconda.org
# rejects it.
#
# The original package is essentially unmaintained, buggy, and contains many
# dubious constructs. I needed to patch it a whole bunch to get it to build on
# Mac OS X, including needing to re-initialize the Autotools scripts to get
# everything to link correctly. So in the end I gave up and decided to not
# just patch up the package, but to actually fork the repository and roll my
# own little release.

{% set name = "dbus-cxx" %}
{% set version = "0.9.2" %}
{% set sha256 = "4f140668f2529ecbdce99afbb89f8a977aa47a36248d5f4943b3660316752ee8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pkgw/dbus-cplusplus/releases/download/v{{ version }}pw/libdbus-c---{{ version }}pw.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1002
  skip: true  # [win]
  run_exports:
    # While this package is in maintenance mode, if any new releases are made it
    # is quite possible that the reason will be some subtle ABI bug, so:
      - {{ pin_subpackage('dbus-cxx', max_pin='x.x.x') }}

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - dbus
    - expat
    - glib
  run:
    # Runtime deps that do not (yet) use run_exports:
    - dbus

test:
  commands:
    - ls $PREFIX/lib/libdbus-c++-glib-1$SHLIB_EXT
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://dbus-cplusplus.sourceforge.net/
  license: LGPLv2+
  license_file: COPYING
  summary: 'C++ bindings for the DBus system'

extra:
  recipe-maintainers:
    - pkgw
