# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "e/xF/vM7N/S5AQNILa6zkfkSnmAdkyFxK9Xs5vPcoZN6mQvBphufacSRoXBFnKQ0PFVw9FOf5Vhq+9oTWcs9Hmxo03P0Lzfv9sVPqUBeuPDWkekROv6mRqdawvsCORt7peQSkbEMSV9tTO8A2sXhXhnxROcYC9t/Et5cPQOtacaj2r8uZotBvFhecKU7uD533gLQNJ6gBtlWi+XIV+IpIXiCQxgpWw0Z8tE6omsOIET7PpK3G+nEbQ+6YFoWJ2ru71tGrSHB4rBd8MM3refSuF3Apg6zZUPF022jVcY6rZGWMnHqnlC8ayn171D0FBg6z89RbGo8P4ZdCBUqjdhTLqRVxOc2nYGkhuXKTa/4Kd8e2/NkPaqsr1GNIHTbCx96zq5f9k2NP+2yFkjOnkdna1PfmV04cMDSXfKQYdma6njO0lxfNuCSwyh/e+D5qhwgtYntFDd7gj/KcEie1ncDr/GSR0dsbW0W3y1Gg+uAsjcmbsv3izuY/xlyCrUO4m7k+XC3RJf6v/bk8DRzNCGroCNwhQoh5vOgYCMukTAHCgeNh4onEJCaADYIwFhyjVUDMqbRLDsNpBFaF3ioEfzAGctxf2Sh9nQ5c2bDadigjlzyNXMzYK/ng56j/oHSNvTiC4/PXkcdwLVZJBS38GAqsDHFL+XfTqsX6MoZFjmR6n0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
