travis:
  secure:
    BINSTAR_TOKEN: e/xF/vM7N/S5AQNILa6zkfkSnmAdkyFxK9Xs5vPcoZN6mQvBphufacSRoXBFnKQ0PFVw9FOf5Vhq+9oTWcs9Hmxo03P0Lzfv9sVPqUBeuPDWkekROv6mRqdawvsCORt7peQSkbEMSV9tTO8A2sXhXhnxROcYC9t/Et5cPQOtacaj2r8uZotBvFhecKU7uD533gLQNJ6gBtlWi+XIV+IpIXiCQxgpWw0Z8tE6omsOIET7PpK3G+nEbQ+6YFoWJ2ru71tGrSHB4rBd8MM3refSuF3Apg6zZUPF022jVcY6rZGWMnHqnlC8ayn171D0FBg6z89RbGo8P4ZdCBUqjdhTLqRVxOc2nYGkhuXKTa/4Kd8e2/NkPaqsr1GNIHTbCx96zq5f9k2NP+2yFkjOnkdna1PfmV04cMDSXfKQYdma6njO0lxfNuCSwyh/e+D5qhwgtYntFDd7gj/KcEie1ncDr/GSR0dsbW0W3y1Gg+uAsjcmbsv3izuY/xlyCrUO4m7k+XC3RJf6v/bk8DRzNCGroCNwhQoh5vOgYCMukTAHCgeNh4onEJCaADYIwFhyjVUDMqbRLDsNpBFaF3ioEfzAGctxf2Sh9nQ5c2bDadigjlzyNXMzYK/ng56j/oHSNvTiC4/PXkcdwLVZJBS38GAqsDHFL+XfTqsX6MoZFjmR6n0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
