travis:
  secure:
    BINSTAR_TOKEN: JpOLr0keugW5ejzCP0WjHSX5c4Hwzd/L4dRRESIbENrRuNtTc5gwihssgaOWH72Qh2mxw8AFOecBH7DnnE36Abh3fj+/UMK0hVb3vVkCk9xHrtfddF5mwLOUqYc3YYzH/h5aExUDWekW0AmyFJCTFS8adWnb3JZCCcfOGPI3n6JP3IZNjqbN6Uxx3mOuQWzduEonwsekgARVSFQzXPivwmfnJfnqGQaCXIuzytEA1WnfXUIryJvnpL82FoYWUNx60Y1Tg1YtNYs4WXFx9vMIVXvRIFq+JoMQdfkiXphkH72et3LdKmfxLJe95hh8rzZ+rYfBbZBHPJGBiCoHSQPHT6X802FUC0sq5CtarMC+QM/sBjBmZTF+1mU6Eva9347inEeNSYAHCHAm5tfZYGbGEvSNzzE4Hm7gzTfF1KLsmf+9ACdPbtJvIYnAVXro0pi9se3VtK8lWpPsxg4Woz5dTGV45o2QM9pcTL2fsvNk2vd73F9i40REfcuFMIAKqfixQwxQkkLyKGk+Er7IQKDXrSc3Saphbfejyan0jrJHi30QJeikmJcX1TDC/ETGqAZ5pFSFXRM3WVQsfp2fw2Gfc6leBzg2/T2aIuXK/c3snDHCO7wGMgbR7oyhvwWHjcKjH02VvTi2i+J0teA73JlQjU2cWfhtWOUBgkA9kiH5C6s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
